import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { PageHeader } from "@/components/admin/page-header";
import { EmptyState } from "@/components/empty-state";
import { StatusBadge } from "@/components/status-badge";
import { formatDate } from "@/lib/format";
import { FolderOpen } from "lucide-react";

export default async function DocumentsPage() {
  const documents = await prisma.document.findMany({
    include: { creator: true },
    orderBy: { createdAt: "desc" },
    take: 100,
  });

  return (
    <div>
      <PageHeader title="Documents" description="Every agreement, invoice, receipt and statement generated by VIDLIX" />
      <div className="p-8">
        {documents.length === 0 ? (
          <EmptyState icon={FolderOpen} title="No documents yet" />
        ) : (
          <div className="rounded-xl border border-neutral-200 bg-white divide-y divide-neutral-100">
            {documents.map((d) => (
              <div key={d.id} className="flex items-center justify-between px-5 py-4 text-sm">
                <div className="flex items-center gap-3">
                  <FolderOpen className="size-4 text-neutral-400" />
                  <div>
                    <div className="font-medium">{d.title}</div>
                    <div className="text-xs text-neutral-400">
                      {d.creator ? (
                        <Link href={`/admin/creators/${d.creator.id}`} className="hover:text-violet-600">{d.creator.name}</Link>
                      ) : null}
                      {" · "}{formatDate(d.createdAt)}
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <StatusBadge status={d.category} />
                  <a href={`/api/files/${d.assetId}`} target="_blank" className="text-xs text-violet-600 hover:underline">View</a>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
